package com.example.kinetic.ui.screens

import androidx.compose.runtime.Immutable

@Immutable
data class Workout(
    val id: String,
    val title: String,
    val category: String,
    val videoUrl: String
)

@Immutable
data class WorkoutListState(
    val workouts: List<Workout>
)

private fun categoryFor(title: String): String {
    return when {
        title.contains("squat", ignoreCase = true) || title.contains("deadlift", ignoreCase = true) || title.contains("leg press", ignoreCase = true) -> "Legs"
        title.contains("lunge", ignoreCase = true) || title.contains("glute", ignoreCase = true) || title.contains("hamstring", ignoreCase = true) || title.contains("calf", ignoreCase = true) -> "Lower Body"
        title.contains("press", ignoreCase = true) || title.contains("fly", ignoreCase = true) || title.contains("bench", ignoreCase = true) -> "Chest"
        title.contains("row", ignoreCase = true) || title.contains("pulldown", ignoreCase = true) || title.contains("pull up", ignoreCase = true) -> "Back"
        title.contains("curl", ignoreCase = true) || title.contains("tricep", ignoreCase = true) || title.contains("wrist", ignoreCase = true) || title.contains("shrug", ignoreCase = true) -> "Arms"
        title.contains("cable", ignoreCase = true) || title.contains("machine", ignoreCase = true) || title.contains("extension", ignoreCase = true) -> "Accessories"
        title.contains("ab", ignoreCase = true) || title.contains("twist", ignoreCase = true) || title.contains("extension", ignoreCase = true) -> "Core"
        else -> "Full Body"
    }
}

private val workoutTitles = listOf(
    "Seated lateral raises",
    "Seated Calf raises",
    "Bulgarian split squats for Glutes",
    "30 Degree Incline Dumbbell Press",
    "Rear Delt Incline Dumbbell Row",
    "Lunges For the Quads",
    "Lunges For the Glutes",
    "Dumbbell lateral raises",
    "Romanian deadlift for the Glutes",
    "Romanian deadlift for the Hamstrings",
    "Lying Lateral Raise",
    "Reverse Dumbbell fly",
    "Reverse Dumbbell Wrist Curls",
    "Dumbbell Wrist Curls",
    "Incline DB Bicep Curls",
    "Concentration Bicep Curls",
    "Decline DB Bench Press",
    "SA triceps overhead",
    "Dumbbell Spider Curl",
    "Dumbbell skull crusher",
    "Dumbbell shoulder press",
    "Single arm dumbbell row",
    "Dumbbell shrugs",
    "Flat dumbbell press",
    "Dumbbell preacher curl",
    "Barbell preacher curl",
    "EZ Bar preacher curl",
    "Dumbbell bicep curl",
    "Dumbbell hammer curl",
    "Dumbbell upright row",
    "Goblet Squat",
    "One hand dumbbell lateral raises",
    "Single leg Romanian deadlift",
    "Dumbbell floor press",
    "Dumbbell twist",
    "Triceps front push",
    "Straight Arm Pulldown",
    "Bar tricep pushdown",
    "Reverse bar tri pushdown",
    "Rope tricep pushdown",
    "SA tricep pushdown",
    "V Grip tricep pushdown",
    "Seated Cable Wrist Curl",
    "Seated Reverse Cable Wrist Curl",
    "Reverse Cable Wrist Curl",
    "Cable Wrist Curl",
    "Cable Wrist Curl",
    "Cable tricep overhead",
    "Cable tricep Kickback",
    "Cable Lateral Raises",
    "Cable Front Raises",
    "Cable ab crunches",
    "High To Low Cable Row",
    "EZ bar cable curl (Wide grip)",
    "EZ bar cable curl (Close grip)",
    "Cable preacher curl",
    "Cable rear delt",
    "Cable abductor",
    "Cable adductor",
    "Single Leg Kickback",
    "Standing cable row",
    "Shotgun Row",
    "Reverse cable flyes",
    "High To Low crossover",
    "Incline cable bi curl",
    "Cable Chest Press",
    "Incline cable fly",
    "Cable biceps curl",
    "Incline chest press",
    "MTS front pulldown",
    "MTS high row",
    "Leg Press",
    "Leg Press Calf Raise",
    "V Squat",
    "Reverse V Squat",
    "Leg press machine",
    "Prone leg curl",
    "Leg extension",
    "Pulldown machine",
    "Chest Press",
    "Triceps extension machine",
    "Close grip lat pulldown",
    "Wide grip lat pulldown",
    "Neutral grip lat pulldown",
    "Reverse close grip lat pulldown",
    "Close grip seated row",
    "SA seated row",
    "Wide Grip seated row",
    "Wide grip pull up",
    "Close grip pull up",
    "Triceps dips",
    "Chest dips",
    "Shoulder press machine",
    "Preacher curl machine",
    "Incline machine fly",
    "T bar row close grip",
    "T bar row wide grip",
    "Lower back Back Extension",
    "Hamstring extension"
)

private val workoutVideoUrls = listOf(
    "https://www.youtube.com/watch?v=NgglZJuYE5I",
    "https://www.youtube.com/watch?v=Nm9f3aZ-X7s",
    "https://www.youtube.com/watch?v=MKzXkvGe9_M",
    "https://www.youtube.com/watch?v=1RssXemCvzw",
    "https://www.youtube.com/watch?v=osOTPbKVwDA",
    "https://www.youtube.com/watch?v=zneQMA7ofKo",
    "https://www.youtube.com/watch?v=6eOs2QwxGVo",
    "https://www.youtube.com/watch?v=zw1gbod1j_4",
    "https://www.youtube.com/watch?v=g8BQGeInIoQ",
    "https://www.youtube.com/watch?v=XlYzCm1BCYA",
    "https://www.youtube.com/watch?v=wcWn4IabrJQ",
    "https://www.youtube.com/watch?v=-soTdOa4ay0",
    "https://www.youtube.com/watch?v=fg6-SrQJ6iA",
    "https://www.youtube.com/watch?v=tc-AdSmh4LE",
    "https://www.youtube.com/watch?v=EM3U2WAreN0",
    "https://www.youtube.com/watch?v=Zj_87jCb-RI",
    "https://www.youtube.com/watch?v=7tyoxFSimZ4",
    "https://www.youtube.com/watch?v=D47UcWFawkk",
    "https://www.youtube.com/watch?v=gEOSJH_TK-s",
    "https://www.youtube.com/watch?v=q1AlpeBNR3s",
    "https://www.youtube.com/watch?v=u7Eefzo7_n8",
    "https://www.youtube.com/watch?v=Ca06jYWP0-I",
    "https://www.youtube.com/watch?v=kxGAyTshGag",
    "https://www.youtube.com/watch?v=lGP8UnBJz88",
    "https://www.youtube.com/watch?v=La4izaU3haw",
    "https://www.youtube.com/watch?v=T43NnW-j6U8",
    "https://www.youtube.com/watch?v=Aq8cXLtOR0U",
    "https://www.youtube.com/watch?v=IPA_Dza0gPE",
    "https://www.youtube.com/watch?v=tbCFYVIBSjo",
    "https://www.youtube.com/watch?v=abIhZxES7ZE",
    "https://www.youtube.com/watch?v=x_v_LGt82xg",
    "https://www.youtube.com/watch?v=lGwQ3Y3ogTw",
    "https://www.youtube.com/watch?v=J6xA5KbxJHY",
    "https://www.youtube.com/watch?v=m3olJesfjEU",
    "https://www.youtube.com/watch?v=kcfg5kIHqnk",
    "https://www.youtube.com/watch?v=Uu3YfFkPCQU",
    "https://www.youtube.com/watch?v=DJIW3s7yMWU",
    "https://www.youtube.com/watch?v=XmMHgFI7xzo",
    "https://www.youtube.com/watch?v=tUsMZjOnego",
    "https://www.youtube.com/watch?v=u3J-fRfo2f8",
    "https://www.youtube.com/watch?v=3zsFo-AednA",
    "https://www.youtube.com/watch?v=YfdGmuZHGaI",
    "https://www.youtube.com/watch?v=y7AzP4YAYyk",
    "https://www.youtube.com/watch?v=5P6ztygjynI",
    "https://www.youtube.com/watch?v=x94mHZH_ivk",
    "https://www.youtube.com/watch?v=0Xd5lENwl0c",
    "https://www.youtube.com/watch?v=HXUu4VSzHkc",
    "https://www.youtube.com/watch?v=DIrPtwox-uo",
    "https://www.youtube.com/watch?v=E4J_qC8dSS0",
    "https://www.youtube.com/watch?v=c1Um4fIHOIA",
    "https://www.youtube.com/watch?v=89_Jn6RIegw",
    "https://www.youtube.com/watch?v=kcAk-RYaWbc",
    "https://www.youtube.com/watch?v=rI_Z8zqgdyM",
    "https://www.youtube.com/watch?v=lcGzxK0eK30",
    "https://www.youtube.com/watch?v=XZ_Z63ERuJ8",
    "https://www.youtube.com/watch?v=X-GTc8H6Tq4",
    "https://www.youtube.com/watch?v=M6_K04_uPxQ",
    "https://www.youtube.com/watch?v=bOWwiAXyMkc",
    "https://www.youtube.com/watch?v=97OJcazSvIQ",
    "https://www.youtube.com/watch?v=FX4ittWnNTM",
    "https://www.youtube.com/watch?v=ucp5_DyA0e0",
    "https://www.youtube.com/watch?v=ym6WvhYAnTA",
    "https://www.youtube.com/watch?v=75_NXbKs_Ts",
    "https://www.youtube.com/watch?v=AfNh_l-7RYk",
    "https://www.youtube.com/watch?v=eaJRCp9PPLw",
    "https://www.youtube.com/watch?v=9ehERN7TdT0",
    "https://www.youtube.com/watch?v=JkPDqyXeqt8",
    "https://www.youtube.com/watch?v=aIrFDP5bhSc",
    "https://www.youtube.com/watch?v=Bh7fJjjmHEs",
    "https://www.youtube.com/watch?v=UOXUDUSHbPw",
    "https://www.youtube.com/watch?v=Z41pIEPGA4k",
    "https://www.youtube.com/watch?v=wBfKOC1-NOw",
    "https://www.youtube.com/watch?v=j2oMK2h-cV8",
    "https://www.youtube.com/watch?v=78hzl3Z0BRg",
    "https://www.youtube.com/watch?v=bLRxrWVOuAM",
    "https://www.youtube.com/watch?v=L956VTaeVIE",
    "https://www.youtube.com/watch?v=SeHAYcW2v8U",
    "https://www.youtube.com/watch?v=pI9QReOplJE",
    "https://www.youtube.com/watch?v=XyfPMsG_lUg",
    "https://www.youtube.com/watch?v=slTkCqGjYV8",
    "https://www.youtube.com/watch?v=Av1nTR4Ybcw",
    "https://www.youtube.com/watch?v=OFNRhZF5c3g",
    "https://www.youtube.com/watch?v=gqblA73PZcQ",
    "https://www.youtube.com/watch?v=4y7UJR1CYnU",
    "https://www.youtube.com/watch?v=dHw006WJLkM",
    "https://www.youtube.com/watch?v=cJO2paNps4w",
    "https://www.youtube.com/watch?v=GgaACXzR2mY",
    "https://www.youtube.com/watch?v=Mlz-l3yDoWc",
    "https://www.youtube.com/watch?v=1ePCqF62MGA",
    "https://www.youtube.com/watch?v=nqIyNBfG2Hg",
    "https://www.youtube.com/watch?v=iS8HkKPFuEY",
    "https://www.youtube.com/watch?v=k7vPyaAR3xs",
    "https://www.youtube.com/watch?v=LFjCnpKyrm0",
    "https://www.youtube.com/watch?v=7W1K9W_6Ryo",
    "https://www.youtube.com/watch?v=WWlJNuxVyRo",
    "https://www.youtube.com/watch?v=Fh-L1IXBMmQ",
    "https://www.youtube.com/watch?v=oxFRrhNh7gU",
    "https://www.youtube.com/watch?v=7cpL2L-qzZc",
    "https://www.youtube.com/watch?v=pI9QReOplJE"
)

val defaultWorkoutListState = WorkoutListState(
    workouts = workoutTitles.mapIndexed { index, title ->
        Workout(
            id = (index + 1).toString(),
            title = title,
            category = categoryFor(title),
            videoUrl = workoutVideoUrls.getOrNull(index) ?: ""
        )
    }
)
